### ISSUE TITLE
Left menu state not remembered after closing and restoring from tray icon

### ISSUE THREAD

**Issue by LB--** [gitterHQ/desktop#144] opened 2016-05-13 17:45 UTC
I'm using the Gitter Desktop client v3.0.3 on Windows 10 64-bit

With the new left menu, there are multiple views that you can switch between on the menu bar. The item you were last on is persisted between page refreshes but the desktop client doesn't have the same mechanic for restore.

Steps to reproduce:

 1. join gitterHQ/change
 2. select the All Conversations view at the top left
 3. Close the window (not minimize) so that only the tray icon remains
 4. Open the window again via the tray icon

At this point the view will be on gitterHQ instead of All Conversations.

It's fine if the view is reset from completely exiting the application, but since it always runs in the background it should be persisted.

**Comment by mydigitalself** [comment] 2016-05-19 13:01
This is getting fixed right now and should be released in the next day or so.

**Closed** 2016-05-19 16:04 UTC
Labels: enhancement

**Comment by DarkSide666** [comment] 2016-07-30 21:36
This is fixed in gittem.im web page, but Gitter desktop client still suffers from this issue and it's quite annoying.
Open gitter destop client, go to some chat room, close client with "X" and it goes to taskbar. When open it from taskbar with doubleclick client opens up, but no in room there you was,but in "search gitter" page.

**Comment by LB--** [comment] 2016-07-30 23:23
Just to note, it's working just fine for me currently.

**Comment by DarkSide666** [comment] 2016-07-30 23:36
I'm using the Gitter Desktop client v3.0.3 on Windows 10 64-bit. Maybe that's the case?

**Comment by LB--** [comment] 2016-07-31 01:09
Ditto here.

**Comment by DarkSide666** [comment] 2016-07-31 19:08
I'm in chatroom as member. Same happens with private chats (one on one).

AND today everything looks ok. Today I can't reproduce this issue anymore. Nothing is changed in my laptop - I even didn't switch it on today. Can this be something on server side?

**Comment by DarkSide666** [comment] 2016-08-01 13:14
Today it's again old story - active chat room is not remembered and it always goes to Search page when I open gitter client from taskbar icon.

**Comment by MadLittleMods** [comment] 2016-08-02 03:14
I use the webapp mostly but the desktop app on Windows 10 seems to behave just fine.

Are you on home or explore when opening Gitter back up?

**Comment by DarkSide666** [comment] 2016-08-02 11:13
> Are you on home or explore when opening the Gitter app back up?

Not sure what you mean by this :)

**Comment by MadLittleMods** [comment] 2016-08-02 13:54
@DarkSide666 Take a screenshot after you restore the window please. https://gitter.im/home or https://gitter.im/home/explore
