### ISSUE TITLE
OS X: Can't paste screen capture image from clipboard

### ISSUE THREAD

**Issue by circa1977** [gitterHQ/desktop#142] opened 2016-05-11 18:47 UTC
On OS X, if I take a screenshot using Ctrl+Shift+Cmd+4, it doesn't paste into the Gitter window.

This does work in other apps, such as HipChat, browser-based email clients, etc. It also worked for me on Ubuntu.

**Comment by MadLittleMods** [comment] 2016-05-11 18:48
Duplicate of https://github.com/gitterHQ/gitter/issues/1040

**Closed by MadLittleMods** 2016-05-11 18:48 UTC
