### ISSUE TITLE
64 bit Windows not starting

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/desktop#65] opened 2015-06-09 19:16 UTC
I'm pretty sure this will be a snapshot issue. 

@trevorah @malditogeek can one of you please look at this

@dgomesbr reported

**Comment by trevorah** [comment] 2015-06-10 11:27
I can jump on this when we next touch the windows app.

**Comment by trevorah** [comment] 2015-06-24 14:37
I cant seem to reproduce this on our 64 bit shitty win7 machine in the office. I'll remove the snapshot pain anyway.

**Comment by trevorah** [comment] 2015-08-20 14:28
Right, I have a windows binary built: http://we.tl/W0hPS1KXgj

**Comment by trevorah** [comment] 2015-08-20 14:29
Does anyone have a list of people who have had this problem?

**Comment by trevorah** [comment] 2015-08-20 15:40
gitter v2.3.3-alpha.1 is fine on windows 8:
![screen shot 2015-08-20 at 16 38 10](https://cloud.githubusercontent.com/assets/298742/9387794/1da66224-475a-11e5-8ffb-ba1c8ad61372.png)

**Comment by trevorah** [comment] 2015-08-20 15:45
@MadLittleMods do you know who else was having this issue?

**Comment by trevorah** [comment] 2015-08-20 16:05
Probably a duplicate of #59.

**Comment by trevorah** [comment] 2015-09-01 13:21
Fixed in 2.3.3

**Closed** 2015-09-01 13:21 UTC
Labels: bug, windows
