### ISSUE TITLE
Option to start minimized 

### ISSUE THREAD

**Issue by ManuelSchneid3r** [gitterHQ/desktop#156] opened 2016-08-03 10:31 UTC
Please add a start minimized option. Graphical or CLI option.

**Comment by MadLittleMods** [comment] 2016-08-03 14:43
Duplicate of https://github.com/gitterHQ/desktop/issues/107

@ManuelSchneid3r There is a PR open to address this which I plan to review soon https://github.com/gitterHQ/desktop/pull/154

**Closed by MadLittleMods** 2016-08-03 14:43 UTC
