### ISSUE TITLE
can't see bottom of "All Conversations" list

### ISSUE THREAD

**Issue by olets** [gitterHQ/desktop#147] opened 2016-05-17 16:55 UTC
Attached: the fade out at the bottom of All Conversations covers at least the last thing in the list. This is on El Capitan

(ps mistakenly left this on the gitter zendesk first, so if any of the maintainers here are part of that group too: sorry, my bad)

<img width="339" alt="inaccessible organizations" src="https://cloud.githubusercontent.com/assets/3282350/15331245/6dc729c4-1c2e-11e6-858c-fe0a84306862.png">

**Comment by MadLittleMods** [comment] 2016-05-17 17:23
Duplicate of https://github.com/gitterHQ/change/issues/40

**Closed by MadLittleMods** 2016-05-17 17:23 UTC
